### ISSUE TITLE
TypeError when dropping content into a collection tile

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#670]
Plone 4.3.11 with collective.cover 1.3b1; dropping a collection into a collection tile results in the following exception:

```python
2016-09-23T18:18:05 ERROR plone.subrequest Error handling subrequest to http://example.org/portada/@@collective.cover.collection/ab3d641c-9d52-45ec-83bd-d25a0a04de62
Traceback (most recent call last):
  File "/opt/plone/tangrama.site/eggs/plone.subrequest-1.7.0-py2.7.egg/plone/subrequest/__init__.py", line 153, in subrequest
    bind=1
  File "/opt/plone/tangrama.site/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/opt/plone/tangrama.site/eggs/plone.tiles-1.8.0-py2.7.egg/plone/tiles/esi.py", line 70, in __call__
    return self.render()
  File "/opt/plone/tangrama.site/eggs/plone.tiles-1.8.0-py2.7.egg/plone/tiles/esi.py", line 54, in render
    u"Override render() or set a class variable 'index' to point to "
TypeError: 'NotImplementedType' object is not callable
```

**Comment by idgserpro** [comment]
This was closed as invalid, so was it a misconfiguration? A missed interface?

**Comment by hvelarde** [comment]
I don't remember but it has nothing to do with this package or it was solved by a newer version of plone.tiles.

**Comment by idgserpro** [comment]
Just for reference if another person comes by, by using plone.tiles > 2.0.0b2, you can see the full traceback instead of `TypeError: 'NotImplementedType' object is not callable` and search for the root cause of the problem. Thanks @hvelarde for https://community.plone.org/t/response-gone-when-using-plone-memoize-on-tiles/3754!
