### ISSUE TITLE
Instance fails to start on site with Mosaic installed

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#821]
Plone 5.1.2 with Mosaic 1.0 installed using the following versions:

```ini
[versions]
plone.app.blocks = 3.1.0
plone.app.drafts = 1.0
plone.app.mosaic = 1.0
plone.app.standardtiles = 1.0
plone.app.tiles = 2.2.1
plone.tiles = 1.5.2
```

After installing collective.cover 2.0b1 instance refuse to start with the following error

```pytb
Traceback (most recent call last):
  File "/opt/plone/buildout/parts/instance/bin/interpreter", line 319, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/opt/plone/buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/opt/plone/buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/opt/plone/buildout/eggs/AccessControl-3.0.14-py2.7-linux-x86_64.egg/AccessControl/security.py", line 165, in protectClass
    permission = getUtility(IPermission, name=permission_id)
  File "/opt/plone/buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.configuration.config.ConfigurationExecutionError: <class 'zope.interface.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'plone.CustomizeContentLayouts')
  in:
  File "/opt/plone/buildout/eggs/plone.app.mosaic-1.0-py2.7.egg/plone/app/mosaic/browser/configure.zcml", line 81.2-86.8
    <browser:page
        name="manage-layouts-from-editor"
        for="*"
        class=".editor.ManageLayoutView"
        permission="plone.CustomizeContentLayouts"
        />
```

**Comment by hvelarde** [comment]
I solved it by adding the following line to the `configure.zcml` file of the project:

```xml
  <include package="plone.app.mosaic" />
```
